/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Атлет
 */
export interface AthleteSetupDTO { 
    /**
     * Идентификатор
     */
    id?: number;
    /**
     * Имя
     */
    firstName: string;
    /**
     * Фамилия
     */
    lastName: string;
    /**
     * Отчество
     */
    middleName?: string;
    /**
     * Пол
     */
    sex: string;
    /**
     * Дата рождения
     */
    birthDate: string;
    /**
     * Город
     */
    city?: string;
    /**
     * Клуб
     */
    club?: string;
}

