/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Группа участников
 */
export interface AthleteGroupDTO { 
    /**
     * Идентификатор
     */
    id: number;
    /**
     * Название
     */
    name: string;
    /**
     * Описание
     */
    description?: string;
}

