/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Краткий вид формат соревнования
 */
export interface RaceFormatJournalDTO { 
    /**
     * Идентификатор формата
     */
    id: number;
    /**
     * Название формата
     */
    name: string;
    /**
     * Тип участия
     */
    type: string;
    /**
     * Дата-время начала
     */
    startTime?: string;
    /**
     * Дата-время завершения
     */
    finishTime?: string;
    /**
     * Статус
     */
    state?: string;
}

