/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Участник соревнования
 */
export interface RaceAthleteSetupDTO { 
    /**
     * Участник
     */
    athleteId: number;
    /**
     * Нагрудный номер
     */
    bibNumber: number;
    /**
     * Группа
     */
    athleteGroupId?: number;
}

