/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RaceAthleteCheckPointDTO } from './raceAthleteCheckPointDTO';
import { RaceAthleteGroupDTO } from './raceAthleteGroupDTO';
import { AthleteDTO } from './athleteDTO';


/**
 * Участник соревнования
 */
export interface RaceAthleteDTO { 
    /**
     * Участник
     */
    athlete: AthleteDTO;
    /**
     * Нагрудный номер
     */
    bibNumber: number;
    /**
     * Статус
     */
    state: string;
    /**
     * Тип участника
     */
    type: string;
    /**
     * Контрольные точки
     */
    checkPoints?: Array<RaceAthleteCheckPointDTO>;
    /**
     * Места в группах
     */
    places?: Array<RaceAthleteGroupDTO>;
}

