/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Тип соревнования
 */
export interface RaceTypeDTO { 
    /**
     * Идентификатор
     */
    id: number;
    /**
     * Название
     */
    name: string;
    /**
     * Тип
     */
    description: string;
}

