/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Контрольная точка
 */
export interface RaceFormatCheckPointSetupDTO { 
    /**
     * Идентификатор
     */
    id: number;
    /**
     * Название
     */
    name: string;
    /**
     * Описание
     */
    description?: string;
    /**
     * Порядковый номер
     */
    orderNumber: number;
    /**
     * Общая дистанция от старта
     */
    totalDistance?: number;
    /**
     * Контрольное время
     */
    checkTime?: string;
    /**
     * Время предполагаемого лидера
     */
    leaderTime?: string;
}

