/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AthleteGroupDTO } from './athleteGroupDTO';


/**
 * Группа участника соревнования
 */
export interface RaceAthleteGroupDTO { 
    /**
     * Идентификатор группы
     */
    group: AthleteGroupDTO;
    /**
     * Место
     */
    place: number;
}

