/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Прохождение контрольной точки участником
 */
export interface RaceAthleteCheckPointDTO { 
    /**
     * Идентификатор контрольной точки
     */
    id: number;
    /**
     * Номер участника
     */
    athleteBibNumber: number;
    /**
     * Космическое время прохождения
     */
    time?: string;
    /**
     * Время прохождения
     */
    raceTime?: string;
    /**
     * Разница по времени с предыдущей контрольной точкой
     */
    prevCheckPointDiffDuration?: string;
    /**
     * Точка пройдена?
     */
    passed: boolean;
    /**
     * Контрольное время истекло
     */
    checkTimeExpired?: boolean;
}

