/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RaceFormatCheckPointDTO } from './raceFormatCheckPointDTO';
import { AthleteGroupDTO } from './athleteGroupDTO';
import { RaceAthleteDTO } from './raceAthleteDTO';


/**
 * Формат соревнования
 */
export interface RaceFormatResultDTO { 
    /**
     * Идентификатор формата
     */
    id: number;
    /**
     * Название формата
     */
    name: string;
    /**
     * Тип участия
     */
    type: string;
    /**
     * Описание
     */
    description?: string;
    /**
     * Дата-время начала
     */
    startTime?: string;
    /**
     * Дата-время завершения
     */
    finishTime?: string;
    /**
     * Группы участников
     */
    athleteGroups?: Array<AthleteGroupDTO>;
    /**
     * Контрольные точки
     */
    checkPoints?: Array<RaceFormatCheckPointDTO>;
    /**
     * Участники
     */
    athletes?: Array<RaceAthleteDTO>;
    /**
     * Статус
     */
    state?: string;
}

