/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Контрольная точка
 */
export interface RaceFormatCheckPointDTO { 
    /**
     * Идентификатор
     */
    id: number;
    /**
     * Название
     */
    name: string;
    /**
     * Описание
     */
    description?: string;
    /**
     * Порядковый номер
     */
    orderNumber: number;
    /**
     * Общая дистанция от старта
     */
    totalDistance?: number;
    /**
     * Контрольное время от старта
     */
    checkDuration?: string;
    /**
     * Контрольное время
     */
    checkTime?: string;
    /**
     * Есть ли контрольное время
     */
    hasCheckTime: boolean;
    /**
     * Время предполагаемого лидера от старта
     */
    leaderDuration?: string;
    /**
     * Время предполагаемого лидера
     */
    leaderTime?: string;
    /**
     * Время предполагаемого лидера от предыдущей КТ
     */
    leaderDiffDuration?: string;
    /**
     * Это старт?
     */
    isStart: boolean;
    /**
     * Это финиш?
     */
    isFinish: boolean;
}

