/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Соревнование
 */
export interface RaceSetupDTO { 
    /**
     * Идентификатор
     */
    id: number;
    /**
     * Название
     */
    name: string;
    /**
     * Описание
     */
    description?: string;
    /**
     * Тип
     */
    raceTypeId: number;
    /**
     * Дата проведения
     */
    date?: string;
    /**
     * Город проведения
     */
    cityId?: number;
}

