server:
  port: 7777

spring:
  application:
    name: krsk-rogain-races
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      ddl-auto: none
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
    drop-first: false
    default-schema: public
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

management:
  endpoints:
    web:
      exposure:
        include: health,info
