server:
  port: 8080

spring:
  datasource:
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
      idle-timeout: 30000           # если неактивно 30 секунд — закрываем соединение
      max-lifetime: 20000           # обновляем соединения каждые 2 минуты
      keepalive-time: 3000          # каждые 45 секунд Hikari пингует БД
      connection-timeout: 15000     # максимум 15 секунд ожидания подключения
      auto-commit: true             # безопасно оставляем true, transaction pooler это поддерживает
      connection-test-query: SELECT 1
      pool-name: HikariPool-Render
