server:
  port: 8888

spring:
  datasource:
    url: jdbc:h2:mem:openapi;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  main:
    web-application-type: servlet

  jpa:
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: false
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
    drop-first: true
    default-schema: public

logging:
  level:
    root: INFO
